spring.application.name=trainingspring1

spring.datasource.url=jdbc:mysql://localhost:3306/sampledb
spring.datasource.username=root
spring.datasource.password=mezase0811
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver